- name: Setup Server
  hosts: ubuntu_servers
  become: yes

  vars:
    new_username: karina
    ssh_public_key: "{{ lookup('file', '~/.ssh/id_rsa.pub') }}"

  tasks:
    - name: Create user
      user:
        name: "{{ new_username }}"
        state: present

    - name: Copy SSH public key for user
      authorized_key:
        user: "{{ new_username }}"
        key: "{{ ssh_public_key }}"
        state: present

    - name: Disable password authentication
      lineinfile:
        dest: /etc/ssh/sshd_config
        regexp: '^PasswordAuthentication'
        line: 'PasswordAuthentication no'
      notify: Restart SSH

    - name: Create directory in /opt/
      file:
        path: /opt/directory_test
        state: directory
        owner: "{{ new_username }}"
        group: "{{ new_username }}"
        mode: '0755'

  handlers:
    - name: Restart SSH
      service:
        name: sshd
        state: restarted


