version: '3.8'

services:
  webserver:
    image: nginx:latest 
    container_name: webserver
    ports:
      - "8080:80"
    volumes:
      - ./config/nginx.conf:/etc/nginx/nginx.conf:ro 
    networks:
      my_network:
        ipv4_address: 10.10.10.4
    depends_on:
      - database

  database:
    image: postgres:latest
    container_name: database
    environment:
      POSTGRES_PASSWORD: root_password
    volumes:
      - database_data:/var/lib/postgresql/data 
    networks:
      my_network:
        ipv4_address: 10.10.10.5 
        aliases:
          - new_db
          - dev_db

volumes:
  database_data: 

networks:
  my_network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 10.10.10.0/28 

